import Header from "@/components/header"
import "../styles/globals.css"
export const metadata = {
  title: 'Blog AI',
  description: 'Generated by Next.js',
  icon: ''
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body>
        <Header/>
        {children}
      </body>
    </html>
  )
}
