import Header from "@/components/header"
import "../styles/globals.css"
import Login from "@/components/Login"
import { SessionProvider } from "../components/SessionProvidor"
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import ChatInput from "@/components/ChatInput"

export const metadata = {
  title: 'Blog AI',
  description: 'Generated by Next.js',
  icon: ''
}


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)
  return (
    <html lang="en">

      <body>
        <SessionProvider session={session}>
          {!session ? (
            <Login/>
          ):(
            <>
              <div>
                <div>
                  <Header />
                </div>
                <div>
                  <ChatInput/>
                </div>
              </div>
            </>
          )}
        </SessionProvider>
        {children}
      </body>
    </html>
  )
}
